stable:
  image: rust:1-slim
  script:
    - rustup component add rustfmt
    - RUST_BACKTRACE=full cargo test --release
    - cargo fmt -- --check
    - cargo run --release -- data/simple-scenario.toml --all
    # Check that when we do a unit conversion it's correct
    # NOTE: We don't do that with km output because the unit conversion leads to some rounding issues
    - diff ./data/scenario-run-cm.csv ./data/scenario-run-m.csv
    - cargo run --release -- data/simple-od-scenario.toml

