[package]
name = "nyx-space"
version = "0.0.10"
authors = ["Christopher Rabotin <christopher.rabotin@gmail.com>"]
description = "A high-fidelity space mission toolkit, with orbit propagation, estimation and some systems engineering"
homepage = "https://github.com/ChristopherRabotin/nyx"
documentation = "https://docs.rs/nyx-space/"
repository = "https://github.com/ChristopherRabotin/nyx"
keywords = ["space", "mission", "design", "orbit", "propagator"]
categories = ["science", "simulation"]
readme = "README.md"
license = "Apache-2.0"
exclude = ["tests/GMAT_scripts/GMAT_V&V_ProcessAndResults.pdf", "examples", "data/*.gz", "rustfmt.toml", "de438*"]

[badges]
maintenance = { status = "actively-developed" }
travis-ci = { repository = "ChristopherRabotin/nyx", branch = "master" }

[dependencies]
nalgebra = "0.18"
log = "0.4"
hifitime = "0.1"
flate2 = { version = "1.0", features = ["rust_backend"], default-features = false }
rand = "0.6"
serde = "1.0"
csv = "1"
hyperdual = "0.3.1"
bytes = "0.4.12"
prost = "0.5"
prost-derive = "0.5"
petgraph = "0.4"

[dev-dependencies]
pretty_env_logger = "0.3"

[features]
default = []
unvalidated = [] # Enable to run unvalidated parts of the code

[profile.dev]
opt-level = 0
debug = true
